name: product-is-builder-jdk17

on: [push]


env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3


jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Clone product IS
        run: |
          git clone https://github.com/wso2/product-is
      - name: Set up Adopt JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Product-IS build with JDK 11 without Integration Tests
        run: |
          cd product-is/
          mvn clean install --batch-mode -Dmaven.test.skip=true | tee mvn-build.log
      - name: Set up Adopt JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Product-IS build with JDK 17 with Integration Tests
        run: |
          ls
          cd modules/integration/
          mvn clean install --batch-mode | tee mvn-build.log
