name: product-is-builder-jdk17

on:
  workflow_dispatch:

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3


jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Set up Adopt JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Build product IS
        run: |
          git clone https://github.com/wso2/product-is
          mvn clean install --batch-mode | tee mvn-build.log

